### ISSUE TITLE
Does the hero selection extraction work?

### ISSUE THREAD

**Issue by pjmagee** [Bphots/LobbyFileParser#2]
Hi, I was trying to build something similar and came across this awesome project. However, I have a hard time understanding the LobbyParameters.

**Comment by qqytqqyt** [comment]
The parameters are probably not updated for the latest version.
Blizzard does not document how we can identify heroes from the lobby file (the temp file created on game loading), but I did find the pattern.
Basically the lobby file contains all players’ hero selections but they are encoded in a specific way at certain location of the file.
The parameters indicate how the heroes are encoded and where.

The location is indicated by ‘offset’ where it is the position in the file relative to the first occurrence of ‘s2mv’.
The other parameters indicate how the heroes are encoded. Basically, each hero has 2 codes depending on whether it is selected by the 1st, 3rd, 5th, 7th, 9th (odd) player or the even ones. Heroes are encoded in alphabet sequence. For instance, if Abathur is 0x01 at even, 0x01 at odd, Alarak is 0x03 at even, 0x02 at odd, then Alexstrasza may be 0x05 at even,  0x03 at odd.

The start figure and the increment of the figures vary in different versions and should be updated in lobby parameters.
The test project is a tool to help to look for proper parameters but does not guarantee to work. If it doesn’t, you may need to populate the parameters manually.

You also need to provide the updated list of hero names in alphabet order along with the lobby parameters.
As long as you provide the right 
ones it should start to work.

**Comment by pjmagee** [comment]
thank you for the explanation
